openmrs.root.url: http://localhost:8050/openmrs/ws/rest/v1
bahmni.login.url: /bahmni/home/#/login?showLoginMessage
server.port: 8100
server.context-path: /dhis-integration/
reports.json: /var/www/bahmni_config/openmrs/apps/reports/reports.json